name: walk
description: A new Flutter project.


publish_to: 'none'

version: 2.1.1+104
environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  animated_toggle_switch: ^0.8.3
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  sleek_circular_slider: ^2.0.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.4
  firebase_analytics: ^11.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  location: ^7.0.1
  multi_select_flutter: ^4.1.3
  pinput: ^5.0.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  soundpool: ^2.4.1
  showcaseview: ^4.0.0
  shared_preferences: 2.3.2
  url_launcher: ^6.3.0
  http: ^1.2.2
  syncfusion_flutter_charts: ^21.1.38
  fl_chart: ^0.70.2
  path_provider: ^2.1.4
  csv: ^6.0.0
  awesome_ripple_animation: ^2.0.0
  percent_indicator: ^4.2.3
  flutter_blue_plus: ^1.34.5
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rounded_loading_button: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_faq: ^1.0.1+1
  cloud_firestore: ^5.4.1
  firebase_crashlytics: ^4.1.2
  sqflite: ^2.3.3+1
  intl_phone_field: ^3.2.0
  geolocator: ^13.0.1
  flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: flutter_3.24_android_hotfix # branch name
      # UPDATE: this fix is now included in the master branch
  tutorial_coach_mark: ^1.2.11
  firebase_auth: ^5.3.0
  firebase_app_check: ^0.3.1+2
  introduction_screen: ^3.1.14
  cloud_functions: ^5.1.1
  loading_animation_widget: ^1.2.1
  package_info_plus: ^8.0.2
  mime: ^2.0.0
  open_file: ^3.5.6
  firebase_storage: ^12.3.2
  intl: ^0.19.0
  share_plus: ^10.0.3
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  lottie: ^3.3.1
  flutter_ota: ^0.1.15


dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/images/tutorial/
    - assets/images/animations/
    - assets/images/tour/
    - assets/images/doctor.png
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          style: italic
