// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqTEo8sY4eEUJdOzl-zl3hDZNN01FXaE',
    appId: '1:205623995747:android:5360479e17b33abfbeb756',
    messagingSenderId: '205623995747',
    projectId: 'walk-90dbf',
    storageBucket: 'walk-90dbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbC4TdVKucChkDMZq01R-0wojfF-BA1ek',
    appId: '1:205623995747:ios:4330aaee35f5ff8cbeb756',
    messagingSenderId: '205623995747',
    projectId: 'walk-90dbf',
    storageBucket: 'walk-90dbf.appspot.com',
    androidClientId: '205623995747-09n68mf2qm883ufacabk4f0b38unpoem.apps.googleusercontent.com',
    iosClientId: '205623995747-hgcurg1hm7q7cthj36be156u4pi6510m.apps.googleusercontent.com',
    iosBundleId: 'com.lifesparktech.walk',
  );

}