
default_platform(:android)

platform :android do
  desc "Build android aab and apk"
  lane :build_android do |options|
    ENV["ANDROID_SDK_ROOT"] = "C:\\Users\\\EASHUBH THAPLIYAL\\AppData\\Local\\Android\\sdk"
    # Clean Project
    sh "./flutter_build.bat clean"
    # Get Packages
    sh "./flutter_build.bat get"
    # Build APK
    sh "./flutter_build.bat apk"
    # Build AAB
    sh "./flutter_build.bat"
  end

  desc "Deploy (Upload to play store)"
  lane :deploy_android do |options|
    track = options[:track] || 'internal' 
    upload_to_play_store(
      track: track,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true, 
    )
  end
end