
default_platform(:android)

platform :android do
  desc "Build android aab and apk"
  lane :build_android do |options|
    ENV["ANDROID_SDK_ROOT"] = "/Users/lifesparktechnologies/Documents/Android"
    ENV["LC_ALL"] = "en_US.UTF-8"
    ENV["LANG"] = "en_US.UTF-8"
    # Clean Project
    sh "flutter_build_script.sh clean"
    # Get Packages
    sh "flutter_build_script.sh get"
    # Build APK
    sh "flutter_build_script.sh apk"
    # Build AAB
    sh "flutter_build_script.sh"
  end

  desc "Deploy (Upload to play store)"
  lane :deploy_android do |options|
    track = options[:track] || 'internal' 
    upload_to_play_store(
      track: track,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      release_status: "draft",
      skip_upload_screenshots: true, 
    )
  end
end